version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules  # Prevents overwriting node_modules
      - ./backend/prisma:/app/prisma  # Persist SQLite database
    environment:
      - NODE_ENV=development
      - JWT_SECRET=your_super_secret_key
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      - backend

  db:
    image: alpine
    volumes:
      - ./backend/prisma:/data
