version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///app/db.sqlite
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    restart: always
    volumes:
      - db_data:/root/db

volumes:
  db_data:
